CREATE TABLE [dbo].[Todo]
(
	[Id] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL PRIMARY KEY,
	[CreationDate] DATETIME2 NOT NULL,
	[LastModified] DATETIME2 NOT NULL,
	[Name] VARCHAR(50) NOT NULL, 
	[Description] NVARCHAR(500) NULL, 
	[Priority] INT NULL, 
	[Responsible] NVARCHAR(50) NULL, 
	[Deadline] DATETIME2 NULL, 
	[Status] NVARCHAR(50) NULL, 
	[CategoryId] UNIQUEIDENTIFIER NULL, 
	[ParentId] UNIQUEIDENTIFIER NULL, 
	[IsDeleted] BIT NULL, 
	CONSTRAINT [FK_Todo_ToCategory] FOREIGN KEY (CategoryId) REFERENCES [Category]([CategoryId])
	)
