CREATE TABLE [dbo].[Log]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[Method] NVARCHAR(50) NULL, 
	[Uri] NVARCHAR(50) NULL, 
	[RequestTime] DATETIME2 NOT NULL, 
	[Header] NVARCHAR(500) NULL, 
	[Body] NVARCHAR(500) NULL, 
	[Query] NVARCHAR(500) NULL
)
